# -*- coding: utf-8 -*-
"""Calculadora de Média Ponderada (5 Provas)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEB5yvpz2hDDluK3klPUwPylSoin7zQg
"""

alunos = []                                                                     # Primeiramente criar a lista vazia de alunos pra não dar ruim

                                                                                # Aqui você escolhe a quantidade de alunos, para teste recomendo apenas 2
quantidade_alunos = int(input("Quantidade de Alunos "))

                                                                                # Aqui o laço vai ser repetir chegar a quantidade de alunos definida
for aluno_ind in range(quantidade_alunos):
    print(f"\n\t Cadastro dos Alunos {aluno_ind + 1}")                          #f é mais pratico para ler strings no caso o indice + 1

                                                                                # Informações do Aluno
    nome = input("Nome do Aluno: ")
    sobrenome = input("Sobrenome do Aluno: ")
    nome_completo = nome + " " + sobrenome                                      #Facilita lá na frente pra ler uma string de uma só vez

                                                                                # Variáveis individuais do aluno
    total_questoes = 5 * 5                                                      # 5 provas, 5 questões cada
    total_acertos = 0
    nota_total = 0
    provas = []                                                                 #Agora criamos a lista de provas vazia

    for i in range(1, 6):                                                       # Loop das 5 provas teminando em 6 pq pytohn começa lendo do zero
        print(f"\nProva {i}")

        while True:                                                             #Definindo um limite de pontos por acertos, para não quebrar meu código lindo
            acertos = int(input("Número Acertos (0 a 5): "))
            if 0 <= acertos <= 5:                                               #O laço principal é o for para você escrever 5 vezes os pontos usando o range para contar a provas
                break
            else:
                print("Errou! Máximo de acertos só entre 0 e 5.")

        peso_fixo = 2.0                                                         # Cada prova vale 2 pontos
        nota = acertos * 0.4                                                    # Cada acerto vale 0.4 → 5 acertos = 2.0

        total_acertos += acertos                                                #Agora usamos aquelas duas variáveis vazias no começo
        nota_total += nota

        provas.append({                                                         #Agora aquela lista vazia do provas está sendo usada
            "Prova": f"Prova {i}",
            "Acertos": acertos,
            "Nota": round(nota, 2)
        })

                                                                                # Cálculos finais do aluno
    media_final = nota_total                                                    # Total de pontos (máximo 10)
    aproveitamento = (total_acertos / total_questoes) * 100                     # Aqui é só um calculo do aproveitamento da aula em porcentagem
    situacao = "Aprovado" if media_final >= 6 else "Reprovado"

                                                                                # Exibir resultado individual
    print("\n\tResultado Final")
    print(f"Aluno: {nome_completo}")
    print(f"Nota Final: {media_final:.2f} / 10.00")                             # O :.2f formata o número com 2 casas decimais, só na hora de exibir, sem mudar o valor real armazenado na memória.
    print(f"Aproveitamento: {aproveitamento:.2f}%")
    print(f"Situação: {situacao}")


    alunos.append({                                                             # Agora sim depois de criar todo processo de cadastrao adcionamos tudo isso a lista vazia lá de cima
        "Nome Completo": nome_completo,
        "Nota Final": round(media_final, 2),                                    #O round aqui é semelhante ao f, a diferença é que round armazena a nota arredondada como número, é eu sei, mas isso realmente faz diferença.
        "Aproveitamento (%)": round(aproveitamento, 2),
        "Situação": situacao
    })

                                                                                # Resumo geral da turma
print("\n\tResumo da Turma")
for aluno in alunos:
    print(f"{aluno['Nome Completo']} - Nota: {aluno['Nota Final']} - Aproveitamento: {aluno['Aproveitamento (%)']}% - {aluno['Situação']}")